/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OverlockRecord = IDL.Record({
  'id' : IDL.Nat,
  'finalAmount' : IDL.Float64,
  'employeeName' : IDL.Text,
  'pcsRate' : IDL.Float64,
  'date' : IDL.Text,
  'rate' : IDL.Float64,
  'articleNo' : IDL.Text,
  'quantity' : IDL.Float64,
});
export const ProductionRecord = IDL.Record({
  'id' : IDL.Nat,
  'finalAmount' : IDL.Float64,
  'dispatchedPcs' : IDL.Float64,
  'date' : IDL.Text,
  'rate' : IDL.Float64,
  'totalPcs' : IDL.Float64,
  'articleNo' : IDL.Text,
  'masterName' : IDL.Text,
  'cutByMaster' : IDL.Float64,
  'percentage' : IDL.Float64,
});
export const TailorRecord = IDL.Record({
  'id' : IDL.Nat,
  'finalAmount' : IDL.Float64,
  'pcsRate' : IDL.Float64,
  'date' : IDL.Text,
  'tailorName' : IDL.Text,
  'color' : IDL.Text,
  'articleNo' : IDL.Text,
  'quantity' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addOverlockRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'addRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'addTailorRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteOverlockRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTailorRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getArticleReport' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getMasterNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMasterReport' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64, IDL.Float64))],
      ['query'],
    ),
  'getOverlockRecords' : IDL.Func([], [IDL.Vec(OverlockRecord)], ['query']),
  'getOverlockReport' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64, IDL.Float64))],
      ['query'],
    ),
  'getRecords' : IDL.Func([], [IDL.Vec(ProductionRecord)], ['query']),
  'getTailorRecords' : IDL.Func([], [IDL.Vec(TailorRecord)], ['query']),
  'getTailorReport' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64, IDL.Float64))],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OverlockRecord = IDL.Record({
    'id' : IDL.Nat,
    'finalAmount' : IDL.Float64,
    'employeeName' : IDL.Text,
    'pcsRate' : IDL.Float64,
    'date' : IDL.Text,
    'rate' : IDL.Float64,
    'articleNo' : IDL.Text,
    'quantity' : IDL.Float64,
  });
  const ProductionRecord = IDL.Record({
    'id' : IDL.Nat,
    'finalAmount' : IDL.Float64,
    'dispatchedPcs' : IDL.Float64,
    'date' : IDL.Text,
    'rate' : IDL.Float64,
    'totalPcs' : IDL.Float64,
    'articleNo' : IDL.Text,
    'masterName' : IDL.Text,
    'cutByMaster' : IDL.Float64,
    'percentage' : IDL.Float64,
  });
  const TailorRecord = IDL.Record({
    'id' : IDL.Nat,
    'finalAmount' : IDL.Float64,
    'pcsRate' : IDL.Float64,
    'date' : IDL.Text,
    'tailorName' : IDL.Text,
    'color' : IDL.Text,
    'articleNo' : IDL.Text,
    'quantity' : IDL.Float64,
  });
  
  return IDL.Service({
    'addOverlockRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'addRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'addTailorRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteOverlockRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTailorRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getArticleReport' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getMasterNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMasterReport' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64, IDL.Float64))],
        ['query'],
      ),
    'getOverlockRecords' : IDL.Func([], [IDL.Vec(OverlockRecord)], ['query']),
    'getOverlockReport' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64, IDL.Float64))],
        ['query'],
      ),
    'getRecords' : IDL.Func([], [IDL.Vec(ProductionRecord)], ['query']),
    'getTailorRecords' : IDL.Func([], [IDL.Vec(TailorRecord)], ['query']),
    'getTailorReport' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64, IDL.Float64))],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };