/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface OverlockRecord {
  'id' : bigint,
  'finalAmount' : number,
  'employeeName' : string,
  'pcsRate' : number,
  'date' : string,
  'size' : string,
  'articleNo' : string,
  'quantity' : number,
}
export interface ProductionRecord {
  'id' : bigint,
  'finalAmount' : number,
  'dispatchedPcs' : number,
  'date' : string,
  'rate' : number,
  'totalPcs' : number,
  'articleNo' : string,
  'masterName' : string,
  'cutByMaster' : number,
  'percentage' : number,
}
export interface TailorRecord {
  'id' : bigint,
  'finalAmount' : number,
  'pcsRate' : number,
  'date' : string,
  'tailorName' : string,
  'color' : string,
  'size' : string,
  'articleNo' : string,
  'quantity' : number,
}
export interface _SERVICE {
  'addOverlockRecord' : ActorMethod<
    [string, string, string, string, number, number, number],
    bigint
  >,
  'addRecord' : ActorMethod<
    [string, string, string, number, number, number, number, number, number],
    bigint
  >,
  'addTailorRecord' : ActorMethod<
    [string, string, string, string, string, number, number, number],
    bigint
  >,
  'deleteOverlockRecord' : ActorMethod<[bigint], boolean>,
  'deleteRecord' : ActorMethod<[bigint], boolean>,
  'deleteTailorRecord' : ActorMethod<[bigint], boolean>,
  'getArticleReport' : ActorMethod<[], Array<[string, number]>>,
  'getMasterNames' : ActorMethod<[], Array<string>>,
  'getMasterReport' : ActorMethod<[], Array<[string, number, number]>>,
  'getOverlockRecords' : ActorMethod<[], Array<OverlockRecord>>,
  'getOverlockReport' : ActorMethod<[], Array<[string, number, number]>>,
  'getRecords' : ActorMethod<[], Array<ProductionRecord>>,
  'getTailorRecords' : ActorMethod<[], Array<TailorRecord>>,
  'getTailorReport' : ActorMethod<[], Array<[string, number, number]>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];