/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DispatchRecord {
  'id' : bigint,
  'date' : string,
  'finalPayment' : number,
  'articleNo' : string,
  'salePrice' : number,
  'dispatchQuantity' : number,
  'percentage' : number,
}
export interface ItemMaster {
  'id' : bigint,
  'sizeXXL' : number,
  'sizeL' : number,
  'sizeM' : number,
  'sizeS' : number,
  'articleNo' : string,
  'sizeXL' : number,
  'totalQuantity' : number,
}
export interface OverlockRecord {
  'id' : bigint,
  'finalAmount' : number,
  'employeeName' : string,
  'pcsRate' : number,
  'date' : string,
  'size' : string,
  'articleNo' : string,
  'quantity' : number,
}
export interface ProductionRecord {
  'id' : bigint,
  'finalAmount' : number,
  'dispatchedPcs' : number,
  'date' : string,
  'rate' : number,
  'totalPcs' : number,
  'articleNo' : string,
  'cutByMaster' : number,
  'partyName' : string,
  'percentage' : number,
}
export interface TailorRecord {
  'id' : bigint,
  'finalAmount' : number,
  'pcsRate' : number,
  'date' : string,
  'tailorName' : string,
  'color' : string,
  'size' : string,
  'articleNo' : string,
  'quantity' : number,
}
export interface _SERVICE {
  'addDispatchRecord' : ActorMethod<
    [string, string, number, number, number, number],
    bigint
  >,
  'addItemMaster' : ActorMethod<
    [string, number, number, number, number, number, number],
    bigint
  >,
  'addOverlockRecord' : ActorMethod<
    [string, string, string, string, number, number, number],
    bigint
  >,
  'addRecord' : ActorMethod<
    [string, string, string, number, number, number, number, number, number],
    bigint
  >,
  'addTailorRecord' : ActorMethod<
    [string, string, string, string, string, number, number, number],
    bigint
  >,
  'deleteDispatchRecord' : ActorMethod<[bigint], boolean>,
  'deleteItemMaster' : ActorMethod<[bigint], boolean>,
  'deleteOverlockRecord' : ActorMethod<[bigint], boolean>,
  'deleteRecord' : ActorMethod<[bigint], boolean>,
  'deleteTailorRecord' : ActorMethod<[bigint], boolean>,
  'getArticleRemainingBySize' : ActorMethod<
    [string],
    [] | [[number, number, number, number, number]]
  >,
  'getArticleReport' : ActorMethod<[], Array<[string, number]>>,
  'getDispatchRecords' : ActorMethod<[], Array<DispatchRecord>>,
  'getDispatchedQtyByArticle' : ActorMethod<[string], number>,
  'getItemMasterByArticle' : ActorMethod<[string], [] | [ItemMaster]>,
  'getItemMasters' : ActorMethod<[], Array<ItemMaster>>,
  'getMasterNames' : ActorMethod<[], Array<string>>,
  'getMasterReport' : ActorMethod<[], Array<[string, number, number]>>,
  'getOverlockRecords' : ActorMethod<[], Array<OverlockRecord>>,
  'getOverlockReport' : ActorMethod<[], Array<[string, number, number]>>,
  'getRecords' : ActorMethod<[], Array<ProductionRecord>>,
  'getTailorRecords' : ActorMethod<[], Array<TailorRecord>>,
  'getTailorReport' : ActorMethod<[], Array<[string, number, number]>>,
  'updateDispatchRecord' : ActorMethod<
    [bigint, string, string, number, number, number, number],
    boolean
  >,
  'updateItemMaster' : ActorMethod<
    [bigint, string, number, number, number, number, number, number],
    boolean
  >,
  'updateOverlockRecord' : ActorMethod<
    [bigint, string, string, string, string, number, number, number],
    boolean
  >,
  'updateRecord' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      number,
      number,
      number,
      number,
      number,
      number,
    ],
    boolean
  >,
  'updateTailorRecord' : ActorMethod<
    [bigint, string, string, string, string, string, number, number, number],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];