/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface OverlockRecord {
    id: bigint;
    finalAmount: number;
    employeeName: string;
    pcsRate: number;
    date: string;
    rate: number;
    articleNo: string;
    quantity: number;
}
export interface ProductionRecord {
    id: bigint;
    finalAmount: number;
    dispatchedPcs: number;
    date: string;
    rate: number;
    totalPcs: number;
    articleNo: string;
    masterName: string;
    cutByMaster: number;
    percentage: number;
}
export interface TailorRecord {
    id: bigint;
    finalAmount: number;
    pcsRate: number;
    date: string;
    tailorName: string;
    color: string;
    articleNo: string;
    quantity: number;
}
export interface backendInterface {
    addOverlockRecord(date: string, articleNo: string, employeeName: string, quantity: number, pcsRate: number, rate: number, finalAmount: number): Promise<bigint>;
    addRecord(date: string, articleNo: string, masterName: string, dispatchedPcs: number, cutByMaster: number, rate: number, percentage: number, totalPcs: number, finalAmount: number): Promise<bigint>;
    addTailorRecord(date: string, articleNo: string, tailorName: string, color: string, quantity: number, pcsRate: number, finalAmount: number): Promise<bigint>;
    deleteOverlockRecord(id: bigint): Promise<boolean>;
    deleteRecord(id: bigint): Promise<boolean>;
    deleteTailorRecord(id: bigint): Promise<boolean>;
    getArticleReport(): Promise<Array<[string, number]>>;
    getMasterNames(): Promise<Array<string>>;
    getMasterReport(): Promise<Array<[string, number, number]>>;
    getOverlockRecords(): Promise<Array<OverlockRecord>>;
    getOverlockReport(): Promise<Array<[string, number, number]>>;
    getRecords(): Promise<Array<ProductionRecord>>;
    getTailorRecords(): Promise<Array<TailorRecord>>;
    getTailorReport(): Promise<Array<[string, number, number]>>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addOverlockRecord(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: number, arg6: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addOverlockRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOverlockRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addRecord(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async addTailorRecord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTailorRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTailorRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteOverlockRecord(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOverlockRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOverlockRecord(arg0);
            return result;
        }
    }
    async deleteRecord(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecord(arg0);
            return result;
        }
    }
    async deleteTailorRecord(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTailorRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTailorRecord(arg0);
            return result;
        }
    }
    async getArticleReport(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticleReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticleReport();
            return result;
        }
    }
    async getMasterNames(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMasterNames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMasterNames();
            return result;
        }
    }
    async getMasterReport(): Promise<Array<[string, number, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMasterReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMasterReport();
            return result;
        }
    }
    async getOverlockRecords(): Promise<Array<OverlockRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverlockRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverlockRecords();
            return result;
        }
    }
    async getOverlockReport(): Promise<Array<[string, number, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverlockReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverlockReport();
            return result;
        }
    }
    async getRecords(): Promise<Array<ProductionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecords();
            return result;
        }
    }
    async getTailorRecords(): Promise<Array<TailorRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTailorRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTailorRecords();
            return result;
        }
    }
    async getTailorReport(): Promise<Array<[string, number, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTailorReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTailorReport();
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
